#!/usr/bin/env node
/**
 * Morphology code tables, from STEPBible's expansions of the codes used in
 * tagged texts:
 *
 *   TEHMC — Translators Expansion of Hebrew Morphology Codes (OpenScriptures'
 *           codes, as in the OSHB and TAHOT: HVqp3ms, HNcmpa, HR/Ncfsa)
 *   TEGMC — Translators Expansion of Greek Morphology Codes (Robinson's
 *           codes, as in TAGNT and most tagged Greek: V-PAI-3S, N-NSM)
 *
 * Both are CC BY 4.0, STEPBible.org, from
 * https://github.com/STEPBible/STEPBible-Data ("Morphology codes" folder).
 * Each full code is written out as the phrase STEPBible gives it; the result
 * is app/core/morph-data.js, which the word study loads when it is first
 * opened.
 *
 *   node scripts/morphology.mjs <TEHMC.txt> <TEGMC.txt>           what would be written
 *   node scripts/morphology.mjs <TEHMC.txt> <TEGMC.txt> --apply   write it
 *
 * Standard library only. A file that yields no codes is an error, not an
 * empty table.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'app/core/morph-data.js');

const args = process.argv.slice(2);
const apply = args.includes('--apply');
const files = args.filter((arg) => !arg.startsWith('--'));
if (files.length !== 2) {
  console.error('usage: node scripts/morphology.mjs <TEHMC.txt> <TEGMC.txt> [--apply]');
  process.exit(2);
}

/**
 * The full-code section of one file: blocks separated by a line holding "$",
 * each a code and its fields on the first line, then the readable phrase and
 * the explanation on the next two.
 */
function readCodes(path, pattern) {
  const text = readFileSync(path, 'utf8').replace(/^﻿/, '');
  const start = text.indexOf('FULL MORPHOLOGY CODES');
  if (start < 0) throw new Error(`${path}: no "FULL MORPHOLOGY CODES" section — is this a STEPBible TEHMC/TEGMC file?`);
  const out = {};
  for (const block of text.slice(start).split(/\r?\n\$\r?\n/)) {
    const lines = block.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    const head = lines.find((line) => pattern.test(line.split('\t')[0]));
    if (!head) continue;
    const at = lines.indexOf(head);
    const code = head.split('\t')[0].trim();
    const phrase = (lines[at + 1] ?? '').replace(/^"|"$/g, '').replace(/\s+/g, ' ').trim();
    if (!phrase || /^Example:/.test(phrase)) continue;
    // The phrase is the parsing; the longer explanation under it is left in
    // STEPBible's file — four times the size, for a sentence a reader who
    // needs it can look up there.
    out[code] = phrase;
  }
  if (!Object.keys(out).length) throw new Error(`${path}: no codes read`);
  return out;
}

const hebrew = readCodes(files[0], /^[HA][A-Za-z0-9]+$/);
const greek = readCodes(files[1], /^[A-Z]+(-[A-Z0-9]+)*$/);

const body = `/**
 * Morphology codes, written out. Generated by scripts/morphology.mjs from
 * STEPBible's TEHMC and TEGMC (Translators Expansion of Hebrew / Greek
 * Morphology Codes), CC BY 4.0, STEPBible.org —
 * https://github.com/STEPBible/STEPBible-Data. Do not edit by hand.
 *
 * code → the code as a phrase
 */

export const HEBREW = ${JSON.stringify(hebrew)};

export const GREEK = ${JSON.stringify(greek)};
`;

console.log(`Hebrew codes: ${Object.keys(hebrew).length}`);
console.log(`Greek codes:  ${Object.keys(greek).length}`);
console.log(`${OUT}: ${(body.length / 1024).toFixed(0)} KB`);
for (const sample of ['HVqp3ms', 'HNcmpa', 'HR']) console.log(`  ${sample} → ${hebrew[sample] ?? '(none)'}`);
for (const sample of ['V-PAI-3S', 'N-NSM']) console.log(`  ${sample} → ${greek[sample] ?? '(none)'}`);
if (apply) {
  writeFileSync(OUT, body);
  console.log('written');
} else {
  console.log('dry run: nothing written (add --apply)');
}
