#!/usr/bin/env node
/**
 * Where an English Bible's verse is in the Hebrew Bible, from STEPBible's
 * TVTMS (Translators Versification Traditions with Methodology for
 * Standardisation), CC BY 4.0, STEPBible.org (Tyndale House, Cambridge) —
 * https://github.com/STEPBible/STEPBible-Data, "Versification" folder.
 *
 * The file closes with the table this needs: "English (NRSV, ESV, KJV etc)"
 * against "Hebrew MT", one verse a row, only where the two differ. Malachi
 * 4:1 is Hebrew 3:19; a psalm's title is English verse 0 and Hebrew verse 1
 * (or 1–2); Isaiah 64:1 is the second half of Hebrew 63:19. Each row is one
 * English verse and the Hebrew verses it is; a row that is not is an error,
 * not a row quietly passed over.
 *
 * The result is app/core/versification-data.js, which the word study and
 * the interlinear line read through core/versification.js.
 *
 *   node scripts/versification.mjs <TVTMS.txt>           what would be written
 *   node scripts/versification.mjs <TVTMS.txt> --apply   write it
 *
 * Standard library only. A file without the table is an error.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { USFM } from '../app/core/formats/books.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'app/core/versification-data.js');

const args = process.argv.slice(2);
const apply = args.includes('--apply');
const [path] = args.filter((arg) => !arg.startsWith('--'));
if (!path) {
  console.error('usage: node scripts/versification.mjs <TVTMS.txt> [--apply]');
  process.exit(2);
}

const lines = readFileSync(path, 'utf8').replace(/^﻿/, '').split(/\r?\n/);
const start = lines.findIndex((line) => /^English \(NRSV, ESV, KJV etc\)\tHebrew MT/.test(line));
if (start < 0) throw new Error(`${path}: no "English … Hebrew MT" table — is this STEPBible's TVTMS?`);

/** SIL/USFM book code, title case as TVTMS writes it → canon id. */
const bookId = (code) => {
  const id = USFM.indexOf(code.toUpperCase()) + 1;
  if (id < 1) throw new Error(`${path}: unknown book ${code}`);
  return id;
};

const map = {};
let rows = 0;
for (const line of lines.slice(start + 1)) {
  // The table runs until the notes on phrasing that close the file.
  if (/^Phrases and Abbreviations/.test(line)) break;
  const [left = '', right = ''] = line.split('\t').map((cell) => cell.trim());
  if (!left || left.startsWith("'") || !right) continue;
  // A leading * marks a row TVTMS flags for its own notes; the mapping stands.
  const english = /^\*?([1-3A-Z][A-Za-z]{2})\.(\d+):(\d+)$/.exec(left);
  if (!english) throw new Error(`${path}: cannot read the English verse "${left}" (expected one verse, as Gen.31:55)`);
  const book = bookId(english[1]);
  // "Psa.51:1,2", "Isa.63:19b", "Num.25:19; 26:1": verses, letters set aside,
  // a chapter carried over from the one before.
  const targets = [];
  let chapter = null;
  const body = right.replace(/^([1-3A-Z][A-Za-z]{2})\./, (_, code) => {
    if (bookId(code) !== book) throw new Error(`${path}: ${left} maps into another book (${right})`);
    return '';
  });
  for (const part of body.split(/[;,]\s*/)) {
    const found = /^(?:(\d+):)?(\d+)([a-z]?)(?:-(\d+))?$/.exec(part.trim());
    if (!found) throw new Error(`${path}: cannot read "${right}" (for ${left})`);
    if (found[1]) chapter = Number(found[1]);
    if (chapter === null) throw new Error(`${path}: "${right}" has no chapter (for ${left})`);
    const from = Number(found[2]);
    const to = found[4] ? Number(found[4]) : from;
    for (let v = from; v <= to; v += 1) targets.push(`${chapter}.${v}`);
  }
  const key = `${book}.${english[2]}.${english[3]}`;
  map[key] = [...new Set([...(map[key] ?? []), ...targets])];
  rows += 1;
}
if (rows < 1000) throw new Error(`${path}: only ${rows} rows read from the English–Hebrew table; expected well over a thousand`);

const body = `/**
 * An English Bible's verse → the Hebrew Bible's verse(s), where they differ.
 * Generated by scripts/versification.mjs from STEPBible's TVTMS, CC BY 4.0,
 * STEPBible.org (Tyndale House, Cambridge) —
 * https://github.com/STEPBible/STEPBible-Data. Changed: the English–Hebrew
 * table only, as "book.chapter.verse" keys (canon book ids) to
 * "chapter.verse" lists, sub-verse letters set aside. Do not edit by hand.
 *
 * Verse 0 is a psalm's title.
 */

export const ENGLISH_TO_HEBREW = ${JSON.stringify(map)};
`;

const sample = (key) => `  ${key} → ${(map[key] ?? ['(same)']).join(', ')}`;
console.log(`rows read: ${rows}`);
console.log(`${OUT}: ${(body.length / 1024).toFixed(0)} KB`);
for (const key of ['39.4.1', '19.51.1', '19.51.0', '29.2.28', '23.64.1', '1.32.1', '1.1.1']) console.log(sample(key));
if (apply) {
  writeFileSync(OUT, body);
  console.log('written');
} else {
  console.log('dry run: nothing written (add --apply)');
}
