/**
 * A morphology code, as words.
 *
 * Two schemes cover almost every tagged original-language text in
 * circulation, and both are written out from STEPBible's tables
 * (`morph-data.js`, generated by scripts/morphology.mjs):
 *
 *   Hebrew and Aramaic  OpenScriptures' codes — the first letter is the
 *                       language (H or A), then parts joined by "/": a prefix,
 *                       the word, a suffix. "HR/Ncfsa" is a preposition and a
 *                       noun.
 *   Greek               Robinson's codes, as in TAGNT: "V-PAI-3S".
 *
 * Anything else — KJV's Strong's tense numbers ("strongMorph:TH8804"), a
 * scheme this does not know — comes back as the code itself, never as a guess.
 *
 * Pure; the tables are passed in, so the 190 KB of them loads only with the
 * word study.
 */

/**
 * @param {string} code as it stands in the text
 * @param {{ HEBREW: Record<string, string>, GREEK: Record<string, string> }} tables
 * @returns {{ code: string, parts: { code: string, said: string|null }[], known: boolean }}
 */
export function describeMorph(code, tables) {
  const raw = String(code ?? '').trim();
  // A scheme prefix ("robinson:", "oshm:") is a label for the code, not part of it;
  // Strong's tense numbers are kept whole — no table here reads them.
  const bare = /^strongMorph:/i.test(raw) ? raw : raw.replace(/^[a-z]+:/i, '');
  if (!bare) return { code: raw, parts: [], known: false };

  if (/^[HA][A-Za-z0-9]/.test(bare) && !bare.includes('-')) {
    const language = bare[0];
    const parts = bare.slice(1).split('/').filter(Boolean).map((part) => {
      const full = `${language}${part}`;
      return { code: part, said: tables.HEBREW[full] ?? null };
    });
    return { code: raw, parts, known: parts.length > 0 && parts.every((p) => p.said) };
  }
  const said = tables.GREEK[bare] ?? null;
  return { code: raw, parts: [{ code: bare, said }], known: Boolean(said) };
}

/** One line for a code: its parts as words, joined, or the code where unknown. */
export function morphLine(code, tables) {
  const { parts } = describeMorph(code, tables);
  if (!parts.length) return String(code ?? '');
  return parts.map((part) => part.said ?? part.code).join(' + ');
}
